### ISSUE TITLE
Webtorrent: not found

### ISSUE THREAD

**Issue by booYah187** [janardonh/KickFlix#1]
Trying to get this running, I am able to view torrent results, can acquire magnet links, but when I attempt to stream or download I receive the following.

Now streaming:
(Title of stream)
sh: 1: webtorrent: not found

And it returns to shell. I have manually performed npm install in the webtorrent folder, all permissions appear to be in order. I have attempted this on Xubuntu, GalliumOS, and Raspbian. Any suggestions? Also, not sure if related, but to run KickFlix.py I need to write out the full file path for it to run.

Best regards, and thanks for all your work on this.

**Comment by janardannn** [comment]
Hello,

The script depends on a npm package called webtorrent and vlc media player
for streaming.

Refer to the readme here
https://github.com/janardonh/KickFlix-cli#installation
